// Dados de demonstração — ilustram a experiência do produto antes da conexão
// com o Supabase. Nenhum destes registros representa um cliente real.
import type {
  Agent,
  Appointment,
  Automation,
  Contact,
  Conversation,
  Integration,
  Lead,
  NotificationItem,
  TeamMember,
} from "./types"

export const demoLeads: Lead[] = [
  {
    id: "lead_1",
    nome: "Marina Castro",
    empresa: "Castro Imóveis",
    whatsapp: "(11) 98211-4420",
    email: "marina@castroimoveis.com.br",
    origem: "Landing Page",
    status: "qualificado",
    responsavel: "Agente IA",
    ultimaInteracao: "há 12 min",
    data: "02/10/2026",
  },
  {
    id: "lead_2",
    nome: "Diego Fontoura",
    empresa: "Fontoura Advocacia",
    whatsapp: "(21) 99021-7731",
    email: "diego@fontouraadv.com.br",
    origem: "WhatsApp",
    status: "negociacao",
    responsavel: "Camila Reis",
    ultimaInteracao: "há 1 h",
    data: "02/10/2026",
  },
  {
    id: "lead_3",
    nome: "Helena Prado",
    empresa: "Prado Odontologia",
    whatsapp: "(31) 98877-2201",
    email: "helena@pradodonto.com.br",
    origem: "Instagram",
    status: "contatado",
    responsavel: "Agente IA",
    ultimaInteracao: "há 3 h",
    data: "01/10/2026",
  },
  {
    id: "lead_4",
    nome: "Rafael Lima",
    empresa: "Lima Contabilidade",
    whatsapp: "(41) 99345-1098",
    email: "rafael@limacontabil.com.br",
    origem: "Indicação",
    status: "novo",
    responsavel: "—",
    ultimaInteracao: "há 5 h",
    data: "01/10/2026",
  },
  {
    id: "lead_5",
    nome: "Beatriz Nunes",
    empresa: "Nunes Estética",
    whatsapp: "(51) 99112-0032",
    email: "beatriz@nunesestetica.com.br",
    origem: "Landing Page",
    status: "demonstracao",
    responsavel: "Camila Reis",
    ultimaInteracao: "há 1 dia",
    data: "30/09/2026",
  },
  {
    id: "lead_6",
    nome: "Thiago Azevedo",
    empresa: "Azevedo Consultoria",
    whatsapp: "(85) 99887-6541",
    email: "thiago@azevedoconsult.com.br",
    origem: "WhatsApp",
    status: "cliente",
    responsavel: "Camila Reis",
    ultimaInteracao: "há 2 dias",
    data: "29/09/2026",
  },
  {
    id: "lead_7",
    nome: "Patrícia Souza",
    empresa: "Souza Arquitetura",
    whatsapp: "(19) 99004-7765",
    email: "patricia@souzaarq.com.br",
    origem: "Indicação",
    status: "perdido",
    responsavel: "Agente IA",
    ultimaInteracao: "há 4 dias",
    data: "27/09/2026",
  },
]

export const demoContacts: Contact[] = [
  {
    id: "contact_1",
    nome: "Marina Castro",
    empresa: "Castro Imóveis",
    whatsapp: "(11) 98211-4420",
    email: "marina@castroimoveis.com.br",
    tags: ["VIP", "Imobiliário"],
    origem: "Landing Page",
    ultimoContato: "há 12 min",
  },
  {
    id: "contact_2",
    nome: "Diego Fontoura",
    empresa: "Fontoura Advocacia",
    whatsapp: "(21) 99021-7731",
    email: "diego@fontouraadv.com.br",
    tags: ["Jurídico"],
    origem: "WhatsApp",
    ultimoContato: "há 1 h",
  },
  {
    id: "contact_3",
    nome: "Thiago Azevedo",
    empresa: "Azevedo Consultoria",
    whatsapp: "(85) 99887-6541",
    email: "thiago@azevedoconsult.com.br",
    tags: ["Cliente ativo", "Consultoria"],
    origem: "WhatsApp",
    ultimoContato: "há 2 dias",
  },
  {
    id: "contact_4",
    nome: "Helena Prado",
    empresa: "Prado Odontologia",
    whatsapp: "(31) 98877-2201",
    email: "helena@pradodonto.com.br",
    tags: ["Saúde"],
    origem: "Instagram",
    ultimoContato: "há 3 h",
  },
]

export const demoConversations: Conversation[] = [
  {
    id: "conv_1",
    nome: "Marina Castro",
    canal: "whatsapp",
    ultimaMensagem: "Perfeito, pode agendar para quinta às 15h.",
    horario: "09:42",
    status: "ia",
    responsavel: "Agente IA",
    naoLidas: 2,
    messages: [
      { id: "m1", sender: "cliente", text: "Olá, gostaria de saber mais sobre os planos de automação.", time: "09:30" },
      { id: "m2", sender: "ia", text: "Olá, Marina! Posso te explicar como a LAUXAI automatiza o atendimento da Castro Imóveis. Você já atende por WhatsApp hoje?", time: "09:31" },
      { id: "m3", sender: "cliente", text: "Sim, mas perdemos muitos leads por demora na resposta.", time: "09:35" },
      { id: "m4", sender: "ia", text: "Entendi. Posso agendar uma demonstração com nosso time para te mostrar como isso muda na prática?", time: "09:38" },
      { id: "m5", sender: "cliente", text: "Perfeito, pode agendar para quinta às 15h.", time: "09:42" },
    ],
  },
  {
    id: "conv_2",
    nome: "Diego Fontoura",
    canal: "whatsapp",
    ultimaMensagem: "Vou validar com a equipe e retorno amanhã.",
    horario: "08:15",
    status: "humano",
    responsavel: "Camila Reis",
    naoLidas: 0,
    messages: [
      { id: "m1", sender: "cliente", text: "Preciso entender melhor o valor da mensalidade.", time: "08:02" },
      { id: "m2", sender: "humano", text: "Bom dia, Diego! Claro, te envio a proposta completa agora.", time: "08:10" },
      { id: "m3", sender: "cliente", text: "Vou validar com a equipe e retorno amanhã.", time: "08:15" },
    ],
  },
  {
    id: "conv_3",
    nome: "Helena Prado",
    canal: "instagram",
    ultimaMensagem: "Vocês atendem clínicas odontológicas?",
    horario: "ontem",
    status: "nao_lida",
    responsavel: "—",
    naoLidas: 1,
    messages: [{ id: "m1", sender: "cliente", text: "Vocês atendem clínicas odontológicas?", time: "ontem" }],
  },
  {
    id: "conv_4",
    nome: "Beatriz Nunes",
    canal: "whatsapp",
    ultimaMensagem: "Agendamento confirmado para sexta-feira.",
    horario: "ontem",
    status: "resolvida",
    responsavel: "Agente IA",
    naoLidas: 0,
    messages: [
      { id: "m1", sender: "cliente", text: "Quero marcar uma avaliação.", time: "ontem" },
      { id: "m2", sender: "ia", text: "Agendamento confirmado para sexta-feira às 10h.", time: "ontem" },
    ],
  },
]

export const demoAutomations: Automation[] = [
  {
    id: "auto_1",
    nome: "Atendimento inicial",
    descricao: "Responde automaticamente o primeiro contato recebido em qualquer canal.",
    status: "ativa",
    ultimaExecucao: "há 8 min",
    execucoes: 1284,
    taxaSucesso: 98,
  },
  {
    id: "auto_2",
    nome: "Qualificação de leads",
    descricao: "Classifica leads automaticamente com base nas respostas da conversa.",
    status: "ativa",
    ultimaExecucao: "há 22 min",
    execucoes: 842,
    taxaSucesso: 94,
  },
  {
    id: "auto_3",
    nome: "Follow-up automático",
    descricao: "Reengaja leads que não respondem após 24 horas.",
    status: "ativa",
    ultimaExecucao: "há 1 h",
    execucoes: 356,
    taxaSucesso: 87,
  },
  {
    id: "auto_4",
    nome: "Recuperação de oportunidade",
    descricao: "Retoma negociações paradas há mais de 5 dias.",
    status: "pausada",
    ultimaExecucao: "há 3 dias",
    execucoes: 128,
    taxaSucesso: 76,
  },
  {
    id: "auto_5",
    nome: "Lembrete de atendimento",
    descricao: "Envia lembretes automáticos antes de agendamentos confirmados.",
    status: "ativa",
    ultimaExecucao: "há 2 h",
    execucoes: 410,
    taxaSucesso: 99,
  },
  {
    id: "auto_6",
    nome: "Transferência para humano",
    descricao: "Identifica quando a IA deve transferir a conversa para um atendente.",
    status: "erro",
    ultimaExecucao: "há 40 min",
    execucoes: 97,
    taxaSucesso: 61,
  },
]

export const demoAgents: Agent[] = [
  {
    id: "agent_1",
    nome: "LAUXAI Sales Agent",
    status: "ativo",
    canal: "WhatsApp",
    objetivo: "Qualificar e converter leads em oportunidades de venda",
    modelo: "LAUXAI Core v2",
    ultimaAtividade: "há 4 min",
  },
  {
    id: "agent_2",
    nome: "Agente de Atendimento",
    status: "ativo",
    canal: "WhatsApp + Instagram",
    objetivo: "Responder dúvidas e direcionar o cliente ao fluxo certo",
    modelo: "LAUXAI Core v2",
    ultimaAtividade: "há 9 min",
  },
  {
    id: "agent_3",
    nome: "Agente de Qualificação",
    status: "ativo",
    canal: "WhatsApp",
    objetivo: "Classificar o nível de interesse e orçamento do lead",
    modelo: "LAUXAI Core v2",
    ultimaAtividade: "há 20 min",
  },
  {
    id: "agent_4",
    nome: "Agente de Agendamento",
    status: "configuracao",
    canal: "Google Calendar",
    objetivo: "Agendar reuniões automaticamente com base na disponibilidade",
    modelo: "LAUXAI Core v2",
    ultimaAtividade: "não configurado",
  },
]

export const demoAppointments: Appointment[] = [
  { id: "ap_1", titulo: "Demonstração do produto", cliente: "Marina Castro", responsavel: "Camila Reis", data: "02/10/2026", horario: "15:00", status: "confirmado" },
  { id: "ap_2", titulo: "Reunião de alinhamento", cliente: "Diego Fontoura", responsavel: "Camila Reis", data: "02/10/2026", horario: "17:30", status: "pendente" },
  { id: "ap_3", titulo: "Avaliação odontológica", cliente: "Helena Prado", responsavel: "Agente IA", data: "03/10/2026", horario: "10:00", status: "confirmado" },
  { id: "ap_4", titulo: "Follow-up comercial", cliente: "Beatriz Nunes", responsavel: "Camila Reis", data: "04/10/2026", horario: "09:30", status: "cancelado" },
]

export const demoIntegrations: Integration[] = [
  { id: "int_whatsapp", nome: "WhatsApp", descricao: "Conecte seu WhatsApp para automatizar atendimento, qualificação e follow-up.", status: "conectado" },
  { id: "int_instagram", nome: "Instagram", descricao: "Centralize mensagens do Instagram Direct junto com os demais canais.", status: "nao_conectado" },
  { id: "int_ai", nome: "AI Provider", descricao: "Provedor de inteligência artificial responsável pelos agentes LAUXAI.", status: "conectado" },
  { id: "int_calendar", nome: "Google Calendar", descricao: "Sincronize agendamentos automaticamente com a sua agenda.", status: "configuracao_necessaria" },
  { id: "int_webhooks", nome: "Webhooks", descricao: "Envie eventos em tempo real para sistemas externos da sua empresa.", status: "nao_conectado" },
  { id: "int_n8n", nome: "n8n", descricao: "Infraestrutura de automação que conecta a LAUXAI aos seus sistemas.", status: "erro" },
]

export const demoNotifications: NotificationItem[] = [
  { id: "n1", titulo: "Novo lead recebido", descricao: "Rafael Lima enviou uma mensagem pela Landing Page.", horario: "há 5 min", lida: false, tipo: "lead" },
  { id: "n2", titulo: "Lead qualificado pela IA", descricao: "Marina Castro foi classificada como lead qualificado.", horario: "há 22 min", lida: false, tipo: "lead" },
  { id: "n3", titulo: "Agendamento confirmado", descricao: "Demonstração com Marina Castro marcada para 02/10 às 15h.", horario: "há 1 h", lida: false, tipo: "agendamento" },
  { id: "n4", titulo: "Automação com erro", descricao: "A automação 'Transferência para humano' falhou 3 vezes.", horario: "há 2 h", lida: true, tipo: "automacao" },
  { id: "n5", titulo: "Integração desconectada", descricao: "O Instagram está desconectado há 2 dias.", horario: "há 1 dia", lida: true, tipo: "integracao" },
  { id: "n6", titulo: "Nova conversa", descricao: "Helena Prado iniciou uma conversa pelo Instagram.", horario: "há 1 dia", lida: true, tipo: "conversa" },
]

export const demoTeam: TeamMember[] = [
  { id: "t1", nome: "Camila Reis", email: "camila@suaempresa.com.br", cargo: "administrador", status: "ativo" },
  { id: "t2", nome: "Eduardo Martins", email: "eduardo@suaempresa.com.br", cargo: "gestor", status: "ativo" },
  { id: "t3", nome: "Juliana Alves", email: "juliana@suaempresa.com.br", cargo: "atendente", status: "pendente" },
]

export const demoActivity = [
  { id: "a1", titulo: "Novo lead recebido", descricao: "Rafael Lima — Lima Contabilidade", horario: "há 5 min" },
  { id: "a2", titulo: "Lead qualificado pela IA", descricao: "Marina Castro — Castro Imóveis", horario: "há 22 min" },
  { id: "a3", titulo: "Agendamento realizado", descricao: "Demonstração marcada com Marina Castro", horario: "há 1 h" },
  { id: "a4", titulo: "Automação executada", descricao: "Follow-up automático enviado para 12 leads", horario: "há 2 h" },
  { id: "a5", titulo: "Conversa transferida para atendimento humano", descricao: "Diego Fontoura — Fontoura Advocacia", horario: "há 3 h" },
]

export const demoWeeklySeries = [
  { dia: "Seg", conversas: 42, leads: 12, conversoes: 3 },
  { dia: "Ter", conversas: 58, leads: 18, conversoes: 5 },
  { dia: "Qua", conversas: 51, leads: 15, conversoes: 4 },
  { dia: "Qui", conversas: 67, leads: 21, conversoes: 7 },
  { dia: "Sex", conversas: 73, leads: 25, conversoes: 9 },
  { dia: "Sáb", conversas: 39, leads: 10, conversoes: 2 },
  { dia: "Dom", conversas: 28, leads: 7, conversoes: 1 },
]

export const demoFunnel = [
  { etapa: "Leads recebidos", valor: 358 },
  { etapa: "Contatados", valor: 294 },
  { etapa: "Qualificados", valor: 176 },
  { etapa: "Em negociação", valor: 84 },
  { etapa: "Convertidos", valor: 41 },
]
